apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::440165694018:role/eksctl-grvchdry-prod-cluster-nodeg-NodeInstanceRole-ZwMx6mnLHvSE
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::440165694018:user/github-actions-grvchdry
      username: github-actions-grvchdry
      groups:
        - system:masters
