services:
  portfolio_nextjs:
    image: gourav-portfolio
    container_name: gourav-portfolio
    working_dir: /app
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - path: .env
        required: false
    build:
      context: .
      dockerfile: Dockerfile
