grafana:
  enabled: true
  adminPassword: "admin123"
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {} 
    retention: 1d
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      cpu: 20m
      memory: 48Mi
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
