grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: "admin123"
  service:
    port: 3000
    targetPort: 3000
  persistence:
    enabled: false
  env:
    GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
    GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: "false"
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    retention: 1d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      cpu: 20m
      memory: 48Mi
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
