replicaCount: 1

image:
  repository: 440165694018.dkr.ecr.ap-south-1.amazonaws.com/grvchdry-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    # Used for IAM Roles for Service Accounts (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::440165694018:role/GrvchdryFrontendRole
  name: "grvchdry-frontend-sa"

podAnnotations:
  # Prometheus scrape config
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "3000"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "alb"
  annotations:
    # AWS ALB Ingress Controller configurations
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:440165694018:certificate/c9bd9f56-0ba5-4576-95a2-979b11e74fe5
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
  hosts:
    - host: "grvchdry.dev"
      paths:
        - path: /
          pathType: Prefix
    - host: "www.grvchdry.dev"
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceMonitor:
  enabled: false
  interval: 15s
  path: /metrics

nodeSelector: {}

tolerations: []

affinity: {}
